import {Section} from '../layout'
import * as React from 'react'
import * as ReactExt from '../react_ext'
import * as Icon from '@heroicons/react/24/solid'
import {useRef, useState} from 'react'
import * as Country from '../country.tsx'
import * as Phone from 'libphonenumber-js/max'
import * as Fetch from '../fetch'
import * as Class from '../class'

// ================
// === Timeline ===
// ================

const events = [
    {
        title: <>Quick response and expert guidance from day one.</>,
        description: (
            <>
                We contact you within 24 hours and help shape your project from the start. We brainstorm together, guide
                design and architecture, and lead you toward a clear plan, even if your idea is still forming.
            </>
        ),
        icon: Icon.HomeIcon,
        iconClass: 'text-zinc-200',
        iconBackgroundClass: 'bg-zinc-800',
    },
    {
        title: <>From idea to a solid plan.</>,
        description: (
            <>
                You get a structured path from concept to a working product. We refine requirements, set priorities and
                create a delivery plan with clear milestones and no surprises.
            </>
        ),
        icon: Icon.MapIcon,
        iconClass: 'text-zinc-200',
        iconBackgroundClass: 'bg-zinc-800',
    },
    {
        title: <>Transparent work and daily communication.</>,
        description: (
            <>
                You’re always informed and involved. You get a shared Discord space with daily updates and direct access
                to the team, so decisions and adjustments happen quickly.
            </>
        ),
        icon: Icon.ChatBubbleOvalLeftEllipsisIcon,
        iconClass: 'text-zinc-200',
        iconBackgroundClass: 'bg-zinc-800',
    },
    {
        title: <>Fast iteration on a handcrafted core</>,
        description: (
            <>
                Your code is written and reviewed by engineers, not generated by AI. We use AI only to accelerate
                analysis and routine tasks, giving you high-quality, long-lasting code delivered faster.
            </>
        ),
        icon: Icon.WrenchScrewdriverIcon,
        iconClass: 'text-zinc-200',
        iconBackgroundClass: 'bg-zinc-800',
    },
    {
        title: <>Focus on real user value.</>,
        description: (
            <>
                You get features that matter and avoid needless complexity. We solve real user problems, design clear
                interfaces and keep operations simple and maintainable.
            </>
        ),
        icon: Icon.UserGroupIcon,
        iconClass: 'text-zinc-200',
        iconBackgroundClass: 'bg-zinc-800',
    },
    {
        title: <>Long-term support and evolution.</>,
        description: (
            <>
                You stay supported well beyond the first release. We maintain, refine and extend your product as needs
                grow, keeping it fast, reliable and aligned with your business.
            </>
        ),
        icon: Icon.HeartIcon,
        iconClass: 'text-accent',
        iconBackgroundClass: 'bg-zinc-800',
    },
]

function Timeline(props: {formSubmitted: boolean}) {
    return (
        <ul role='list'>
            {events.map((event, ix) => {
                const active = props.formSubmitted && ix == 0
                const inactive = props.formSubmitted && ix != 0
                const iconClass = Class.names(event.iconClass, active ? 'animate-pulse' : '')
                const liClassName = inactive ? 'opacity-20' : active ? 'animate-pulse' : ''
                return (
                    <li
                        key={ix}
                        className={Class.names(liClassName, 'transition-opacity duration-300')}
                    >
                        <div className='relative pb-8'>
                            {ix !== events.length - 1 ? (
                                <div
                                    aria-hidden='true'
                                    className='absolute top-4 left-4 -ml-px h-full w-0.5 bg-zinc-800'
                                />
                            ) : null}
                            <div className='relative flex space-x-3'>
                                <div>
                                    <span
                                        className={Class.names(
                                            event.iconBackgroundClass,
                                            'flex size-8 items-center justify-center rounded-full',
                                        )}
                                    >
                                        <event.icon
                                            aria-hidden='true'
                                            className={Class.names(iconClass, 'size-5')}
                                        />
                                    </span>
                                </div>
                                <div className='flex min-w-0 flex-1 justify-between space-x-4 pt-1'>
                                    <div>
                                        <h4> {event.title} </h4>
                                        <span className='text-sm'> {event.description} </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                )
            })}
        </ul>
    )
}

// ===================
// === ContactForm ===
// ===================

export function ContactForm({onSubmit}: {onSubmit: () => void}) {
    const formRef = useRef<HTMLFormElement>(null)
    const phoneNumberRef = useRef<HTMLInputElement>(null)
    const [regionName, setRegionName, regionNameRef] = ReactExt.useStateRef('')
    const phoneParser = useRef(new Phone.AsYouType())

    const updateCountryFromNumber = React.useCallback(
        (number: string) => {
            const numberNorm = number.replace(/\s/g, '')
            if (numberNorm.startsWith('+')) {
                const slice = numberNorm.slice(1)
                const overlapping = Country.overlapping.find(t => slice.startsWith(t.code))
                const country = Object.values(Country.byName).find(t => slice.startsWith(t.code))
                const region = overlapping || country
                if (region != null) {
                    if (regionNameRef.current !== region.name) {
                        setRegionName(region.name)
                    }
                    return
                }
            }
            if (regionNameRef.current !== '') {
                setRegionName('')
            }
        },
        [regionNameRef, setRegionName],
    )

    const setNumber = React.useCallback(
        (numberRaw: string) => {
            const phoneNumerRefCurrent = phoneNumberRef.current
            if (phoneNumerRefCurrent == null) return
            phoneParser.current.reset()
            const number = phoneParser.current.input(numberRaw)
            phoneNumerRefCurrent.value = number
            updateCountryFromNumber(number)
        },
        [updateCountryFromNumber],
    )

    const onPhoneInputChange = React.useCallback(
        (event: React.ChangeEvent<HTMLInputElement>) => {
            setNumber(event.target.value)
            const validity = phoneParser.current.isValid() ? '' : 'Invalid phone number'
            event.target.setCustomValidity(validity)
        },
        [setNumber],
    )

    // Automatically set region based on IP information.
    React.useEffect(() => {
        Fetch.withTimeout('https://ipwho.is/', 5000).then(data =>
            setRegionName(Country.byIso2[data.country_code]?.name ?? ''),
        )
    }, [setRegionName])

    // On region change, update the number.
    React.useEffect(() => {
        const numberInput = phoneNumberRef.current
        const country = Country.byName[regionName]
        if (numberInput != null && country != null) {
            const number = numberInput.value
            const numberNorm = number.replace(/\s/g, '')
            if (numberNorm.startsWith('+')) {
                const slice = numberNorm.slice(1)
                if (!slice.startsWith(country.code)) {
                    const nationalNumber = phoneParser.current.getNumber()?.nationalNumber || ''
                    setNumber(`+${country.code} ${nationalNumber}`)
                }
            } else {
                setNumber(`+${country.code} ${number}`)
            }
        }
    }, [regionName, setNumber])

    // Form submit logic.
    React.useEffect(() => {
        const form = formRef.current!
        async function go(e: SubmitEvent) {
            onSubmit()
            e.preventDefault()

            const formData = Object.fromEntries(new FormData(form))
            const phone = formData.phoneNumber
            const payload = {
                firstName: formData.firstName,
                lastName: formData.lastName,
                email: formData.email,
                phone,
                message: formData.message,
            }

            try {
                const url = 'https://website-form-submission.wojciech-danilo.workers.dev'
                const res = await fetch(url, {
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify(payload),
                })

                if (res.ok) {
                    form.reset()
                } else {
                    console.log('Error while submitting the form.')
                }
            } catch (err) {
                console.log('Error while submitting the form.', err)
            }
        }

        form.addEventListener('submit', go)
        return () => form.removeEventListener('submit', go)
    }, [onSubmit])

    return (
        <form
            ref={formRef}
            action='#'
            method='POST'
            className='lg:flex-auto'
        >
            <div className='flex flex-col gap-6'>
                <div className='flex gap-6 flex-col sm:flex-row'>
                    <div className='grow'>
                        <label
                            htmlFor='firstName'
                            className='block font-semibold text-zinc-200'
                        >
                            First name
                        </label>
                        <div className='mt-2.5'>
                            <input
                                name='firstName'
                                type='text'
                                required
                                autoComplete='given-name'
                                className='block w-full rounded-md px-3.5 py-3 outline-1 -outline-offset-1 outline-zinc-700 backdrop-blur-sm placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-zinc-400'
                            />
                        </div>
                    </div>

                    <div className='grow'>
                        <label
                            htmlFor='lastName'
                            className='block font-semibold text-zinc-200'
                        >
                            Last name
                        </label>
                        <div className='mt-2.5'>
                            <input
                                name='lastName'
                                type='text'
                                required
                                autoComplete='family-name'
                                className='block w-full rounded-md px-3.5 py-3 outline-1 -outline-offset-1 outline-zinc-700 backdrop-blur-sm placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-zinc-300'
                            />
                        </div>
                    </div>
                </div>
                <div>
                    <label
                        htmlFor='email'
                        className='block font-semibold text-zinc-200'
                    >
                        Email address
                    </label>
                    <div className='mt-2.5'>
                        <input
                            id='email'
                            name='email'
                            type='email'
                            required
                            autoComplete='email'
                            className='block w-full rounded-md px-3.5 py-3 outline-1 -outline-offset-1 outline-zinc-700 backdrop-blur-sm placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-zinc-300'
                        />
                    </div>
                </div>

                <div>
                    <label
                        htmlFor='phoneNumber'
                        className='block font-semibold text-zinc-200'
                    >
                        Phone number
                    </label>
                    <input
                        ref={phoneNumberRef}
                        onChange={e => onPhoneInputChange(e)}
                        name='phoneNumber'
                        type='tel'
                        required
                        autoComplete='tel-national'
                        className='mt-2.5 block w-full rounded-md px-3.5 py-3 outline-1 -outline-offset-1 outline-zinc-700 backdrop-blur-sm placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-zinc-300'
                    />
                    <select
                        value={regionName || ''}
                        onChange={e => setRegionName(e.target.value)}
                        name='country'
                        required
                        className='mt-2.5 w-full rounded-md outline outline-1 outline-zinc-700 focus:outline-2 focus:outline-zinc-300'
                        style={{
                            // Padding does not work in Safari
                            height: '44px',
                            textIndent: '10px',
                        }}
                    >
                        <option
                            value=''
                            disabled
                            selected
                        >
                            Select phone prefix
                        </option>

                        {Country.overlapping.map(region => (
                            <option
                                hidden
                                value={region.name}
                            >
                                {region.name} (+{region.code})
                            </option>
                        ))}

                        {Object.values(Country.byName).map(country => (
                            <option value={country.name}>
                                {country.name} (+
                                {country.code})
                            </option>
                        ))}
                    </select>
                </div>
            </div>
            <div className='mt-10'>
                <button
                    type='submit'
                    className='cursor-pointer block w-full rounded-md bg-accent px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-xs focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600'
                >
                    Let’s talk
                </button>
            </div>
            <p className='mt-4 text-sm/6 text-gray-500'>
                By submitting this form, I agree to the{' '}
                <a
                    href='#'
                    className='whitespace-nowrap text-zinc-200'
                >
                    privacy policy
                </a>
                .
            </p>
        </form>
    )
}

// =================
// === Component ===
// =================

export const Component = React.forwardRef<HTMLDivElement>((_, ref) => {
    const [formSubmitted, setFormSubmitted] = useState(false)
    return (
        <div ref={ref}>
            <div className='dark-theme min-h-screen relative'>
                <Section
                    className='!absolute h-full !max-w-screen-3xl'
                    background={<div className='w-full h-full bg-zinc-900' />}
                />

                <Section background={<div className='w-full h-full' />}>
                    <div className='w-full flex justify-center'>
                        <div className='max-w-md lg:max-w-none w-full'>
                            <div className='lg:items-center lg:text-center lg:mx-auto'>
                                <h1>
                                    Let's work <br className='xs:hidden' /> together.
                                </h1>
                                <h3>
                                    From first contact to final delivery, we build your product with clarity and care.
                                </h3>
                            </div>
                            <div className='relative'>
                                <div className='pt-16 flex justify-center flex-col lg:flex-row'>
                                    <div className='lg:w-0 grow'>
                                        <Timeline formSubmitted={formSubmitted} />
                                    </div>

                                    <div
                                        className={Class.names(
                                            'lg:w-0 pt-8 lg:pt-0 transition-all duration-300 overflow-hidden',
                                            formSubmitted ? '' : 'grow',
                                        )}
                                    >
                                        <div className='flex flex-col gap-16 sm:gap-y-20 lg:flex-row lg:pl-16 pl-1 pr-1'>
                                            <ContactForm onSubmit={() => setFormSubmitted(true)} />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </Section>
            </div>
        </div>
    )
})
