interface Country {
    name: string
    code: string
    iso2: string
}

export const byName: Record<string, Country> = Object.fromEntries(
    Object.entries({
        'Afghanistan': {iso2: 'AF', code: '93'},
        'Aland Islands': {iso2: 'AX', code: '358'},
        'Albania': {iso2: 'AL', code: '355'},
        'Algeria': {iso2: 'DZ', code: '213'},
        'American Samoa': {iso2: 'AS', code: '1'},
        'Andorra': {iso2: 'AD', code: '376'},
        'Angola': {iso2: 'AO', code: '244'},
        'Anguilla': {iso2: 'AI', code: '1'},
        'Antigua and Barbuda': {iso2: 'AG', code: '1'},
        'Argentina': {iso2: 'AR', code: '54'},
        'Armenia': {iso2: 'AM', code: '374'},
        'Aruba': {iso2: 'AW', code: '297'},
        'Australia': {iso2: 'AU', code: '61'},
        'Austria': {iso2: 'AT', code: '43'},
        'Azerbaijan': {iso2: 'AZ', code: '994'},

        'Bahamas': {iso2: 'BS', code: '1'},
        'Bahrain': {iso2: 'BH', code: '973'},
        'Bangladesh': {iso2: 'BD', code: '880'},
        'Barbados': {iso2: 'BB', code: '1'},
        'Belarus': {iso2: 'BY', code: '375'},
        'Belgium': {iso2: 'BE', code: '32'},
        'Belize': {iso2: 'BZ', code: '501'},
        'Benin': {iso2: 'BJ', code: '229'},
        'Bermuda': {iso2: 'BM', code: '1'},
        'Bhutan': {iso2: 'BT', code: '975'},
        'Bolivia': {iso2: 'BO', code: '591'},
        'Bosnia and Herzegovina': {iso2: 'BA', code: '387'},
        'Botswana': {iso2: 'BW', code: '267'},
        'Brazil': {iso2: 'BR', code: '55'},
        'British Virgin Islands': {iso2: 'VG', code: '1'},
        'Brunei': {iso2: 'BN', code: '673'},
        'Bulgaria': {iso2: 'BG', code: '359'},
        'Burkina Faso': {iso2: 'BF', code: '226'},
        'Burundi': {iso2: 'BI', code: '257'},

        'Cambodia': {iso2: 'KH', code: '855'},
        'Cameroon': {iso2: 'CM', code: '237'},
        'Canada': {iso2: 'CA', code: '1'},
        'Cape Verde': {iso2: 'CV', code: '238'},
        'Cayman Islands': {iso2: 'KY', code: '1'},
        'Central African Republic': {iso2: 'CF', code: '236'},
        'Chad': {iso2: 'TD', code: '235'},
        'Chile': {iso2: 'CL', code: '56'},
        'China': {iso2: 'CN', code: '86'},
        'Colombia': {iso2: 'CO', code: '57'},
        'Comoros': {iso2: 'KM', code: '269'},
        'Congo': {iso2: 'CG', code: '242'},
        'Congo (DRC)': {iso2: 'CD', code: '243'},
        'Cook Islands': {iso2: 'CK', code: '682'},
        'Costa Rica': {iso2: 'CR', code: '506'},
        'Côte d’Ivoire': {iso2: 'CI', code: '225'},
        'Croatia': {iso2: 'HR', code: '385'},
        'Cuba': {iso2: 'CU', code: '53'},
        'Curaçao': {iso2: 'CW', code: '599'},
        'Cyprus': {iso2: 'CY', code: '357'},
        'Czechia': {iso2: 'CZ', code: '420'},

        'Denmark': {iso2: 'DK', code: '45'},
        'Djibouti': {iso2: 'DJ', code: '253'},
        'Dominica': {iso2: 'DM', code: '1'},
        'Dominican Republic': {iso2: 'DO', code: '1'},

        'Ecuador': {iso2: 'EC', code: '593'},
        'Egypt': {iso2: 'EG', code: '20'},
        'El Salvador': {iso2: 'SV', code: '503'},
        'Equatorial Guinea': {iso2: 'GQ', code: '240'},
        'Eritrea': {iso2: 'ER', code: '291'},
        'Estonia': {iso2: 'EE', code: '372'},
        'Eswatini': {iso2: 'SZ', code: '268'},
        'Ethiopia': {iso2: 'ET', code: '251'},

        'Falkland Islands': {iso2: 'FK', code: '500'},
        'Faroe Islands': {iso2: 'FO', code: '298'},
        'Fiji': {iso2: 'FJ', code: '679'},
        'Finland': {iso2: 'FI', code: '358'},
        'France': {iso2: 'FR', code: '33'},
        'French Guiana': {iso2: 'GF', code: '594'},
        'French Polynesia': {iso2: 'PF', code: '689'},

        'Gabon': {iso2: 'GA', code: '241'},
        'Gambia': {iso2: 'GM', code: '220'},
        'Georgia': {iso2: 'GE', code: '995'},
        'Germany': {iso2: 'DE', code: '49'},
        'Ghana': {iso2: 'GH', code: '233'},
        'Gibraltar': {iso2: 'GI', code: '350'},
        'Greece': {iso2: 'GR', code: '30'},
        'Greenland': {iso2: 'GL', code: '299'},
        'Grenada': {iso2: 'GD', code: '1'},
        'Guadeloupe': {iso2: 'GP', code: '590'},
        'Guam': {iso2: 'GU', code: '1'},
        'Guatemala': {iso2: 'GT', code: '502'},
        'Guernsey': {iso2: 'GG', code: '44'},
        'Guinea': {iso2: 'GN', code: '224'},
        'Guinea-Bissau': {iso2: 'GW', code: '245'},
        'Guyana': {iso2: 'GY', code: '592'},

        'Haiti': {iso2: 'HT', code: '509'},
        'Honduras': {iso2: 'HN', code: '504'},
        'Hong Kong': {iso2: 'HK', code: '852'},
        'Hungary': {iso2: 'HU', code: '36'},

        'Iceland': {iso2: 'IS', code: '354'},
        'India': {iso2: 'IN', code: '91'},
        'Indonesia': {iso2: 'ID', code: '62'},
        'Iran': {iso2: 'IR', code: '98'},
        'Iraq': {iso2: 'IQ', code: '964'},
        'Ireland': {iso2: 'IE', code: '353'},
        'Isle of Man': {iso2: 'IM', code: '44'},
        'Israel': {iso2: 'IL', code: '972'},
        'Italy': {iso2: 'IT', code: '39'},

        'Jamaica': {iso2: 'JM', code: '1'},
        'Japan': {iso2: 'JP', code: '81'},
        'Jersey': {iso2: 'JE', code: '44'},
        'Jordan': {iso2: 'JO', code: '962'},

        'Kazakhstan': {iso2: 'KZ', code: '7'},
        'Kenya': {iso2: 'KE', code: '254'},
        'Kiribati': {iso2: 'KI', code: '686'},
        'Kosovo': {iso2: 'XK', code: '383'},
        'Kuwait': {iso2: 'KW', code: '965'},
        'Kyrgyzstan': {iso2: 'KG', code: '996'},

        'Laos': {iso2: 'LA', code: '856'},
        'Latvia': {iso2: 'LV', code: '371'},
        'Lebanon': {iso2: 'LB', code: '961'},
        'Lesotho': {iso2: 'LS', code: '266'},
        'Liberia': {iso2: 'LR', code: '231'},
        'Libya': {iso2: 'LY', code: '218'},
        'Liechtenstein': {iso2: 'LI', code: '423'},
        'Lithuania': {iso2: 'LT', code: '370'},
        'Luxembourg': {iso2: 'LU', code: '352'},

        'Macau': {iso2: 'MO', code: '853'},
        'Madagascar': {iso2: 'MG', code: '261'},
        'Malawi': {iso2: 'MW', code: '265'},
        'Malaysia': {iso2: 'MY', code: '60'},
        'Maldives': {iso2: 'MV', code: '960'},
        'Mali': {iso2: 'ML', code: '223'},
        'Malta': {iso2: 'MT', code: '356'},
        'Marshall Islands': {iso2: 'MH', code: '692'},
        'Martinique': {iso2: 'MQ', code: '596'},
        'Mauritania': {iso2: 'MR', code: '222'},
        'Mauritius': {iso2: 'MU', code: '230'},
        'Mayotte': {iso2: 'YT', code: '262'},
        'Mexico': {iso2: 'MX', code: '52'},
        'Micronesia': {iso2: 'FM', code: '691'},
        'Moldova': {iso2: 'MD', code: '373'},
        'Monaco': {iso2: 'MC', code: '377'},
        'Mongolia': {iso2: 'MN', code: '976'},
        'Montenegro': {iso2: 'ME', code: '382'},
        'Montserrat': {iso2: 'MS', code: '1'},
        'Morocco': {iso2: 'MA', code: '212'},
        'Mozambique': {iso2: 'MZ', code: '258'},
        'Myanmar': {iso2: 'MM', code: '95'},

        'Namibia': {iso2: 'NA', code: '264'},
        'Nauru': {iso2: 'NR', code: '674'},
        'Nepal': {iso2: 'NP', code: '977'},
        'Netherlands': {iso2: 'NL', code: '31'},
        'New Caledonia': {iso2: 'NC', code: '687'},
        'New Zealand': {iso2: 'NZ', code: '64'},
        'Nicaragua': {iso2: 'NI', code: '505'},
        'Niger': {iso2: 'NE', code: '227'},
        'Nigeria': {iso2: 'NG', code: '234'},
        'Niue': {iso2: 'NU', code: '683'},
        'Norfolk Island': {iso2: 'NF', code: '672'},
        'North Korea': {iso2: 'KP', code: '850'},
        'North Macedonia': {iso2: 'MK', code: '389'},
        'Northern Mariana Islands': {iso2: 'MP', code: '1'},
        'Norway': {iso2: 'NO', code: '47'},

        'Oman': {iso2: 'OM', code: '968'},

        'Pakistan': {iso2: 'PK', code: '92'},
        'Palau': {iso2: 'PW', code: '680'},
        'Palestine': {iso2: 'PS', code: '970'},
        'Panama': {iso2: 'PA', code: '507'},
        'Papua New Guinea': {iso2: 'PG', code: '675'},
        'Paraguay': {iso2: 'PY', code: '595'},
        'Peru': {iso2: 'PE', code: '51'},
        'Philippines': {iso2: 'PH', code: '63'},
        'Pitcairn Islands': {iso2: 'PN', code: '64'},
        'Poland': {iso2: 'PL', code: '48'},
        'Portugal': {iso2: 'PT', code: '351'},
        'Puerto Rico': {iso2: 'PR', code: '1'},

        'Qatar': {iso2: 'QA', code: '974'},

        'Reunion': {iso2: 'RE', code: '262'},
        'Romania': {iso2: 'RO', code: '40'},
        'Russia': {iso2: 'RU', code: '7'},
        'Rwanda': {iso2: 'RW', code: '250'},

        'Saint Barthelemy': {iso2: 'BL', code: '590'},
        'Saint Helena': {iso2: 'SH', code: '290'},
        'Saint Kitts and Nevis': {iso2: 'KN', code: '1'},
        'Saint Lucia': {iso2: 'LC', code: '1'},
        'Saint Martin': {iso2: 'MF', code: '590'},
        'Saint Pierre and Miquelon': {iso2: 'PM', code: '508'},
        'Saint Vincent and the Grenadines': {iso2: 'VC', code: '1'},

        'Samoa': {iso2: 'WS', code: '685'},
        'San Marino': {iso2: 'SM', code: '378'},
        'Sao Tome and Principe': {iso2: 'ST', code: '239'},
        'Saudi Arabia': {iso2: 'SA', code: '966'},
        'Senegal': {iso2: 'SN', code: '221'},
        'Serbia': {iso2: 'RS', code: '381'},
        'Seychelles': {iso2: 'SC', code: '248'},
        'Sierra Leone': {iso2: 'SL', code: '232'},
        'Singapore': {iso2: 'SG', code: '65'},
        'Sint Maarten': {iso2: 'SX', code: '1'},
        'Slovakia': {iso2: 'SK', code: '421'},
        'Slovenia': {iso2: 'SI', code: '386'},
        'Solomon Islands': {iso2: 'SB', code: '677'},
        'Somalia': {iso2: 'SO', code: '252'},
        'South Africa': {iso2: 'ZA', code: '27'},
        'South Korea': {iso2: 'KR', code: '82'},
        'South Sudan': {iso2: 'SS', code: '211'},
        'Spain': {iso2: 'ES', code: '34'},
        'Sri Lanka': {iso2: 'LK', code: '94'},
        'Sudan': {iso2: 'SD', code: '249'},
        'Suriname': {iso2: 'SR', code: '597'},
        'Svalbard and Jan Mayen': {iso2: 'SJ', code: '47'},
        'Sweden': {iso2: 'SE', code: '46'},
        'Switzerland': {iso2: 'CH', code: '41'},
        'Syria': {iso2: 'SY', code: '963'},

        'Taiwan': {iso2: 'TW', code: '886'},
        'Tajikistan': {iso2: 'TJ', code: '992'},
        'Tanzania': {iso2: 'TZ', code: '255'},
        'Thailand': {iso2: 'TH', code: '66'},
        'Timor-Leste': {iso2: 'TL', code: '670'},
        'Togo': {iso2: 'TG', code: '228'},
        'Tokelau': {iso2: 'TK', code: '690'},
        'Tonga': {iso2: 'TO', code: '676'},
        'Trinidad and Tobago': {iso2: 'TT', code: '1'},
        'Tunisia': {iso2: 'TN', code: '216'},
        'Turkey': {iso2: 'TR', code: '90'},
        'Turkmenistan': {iso2: 'TM', code: '993'},
        'Turks and Caicos Islands': {iso2: 'TC', code: '1'},
        'Tuvalu': {iso2: 'TV', code: '688'},

        'Uganda': {iso2: 'UG', code: '256'},
        'Ukraine': {iso2: 'UA', code: '380'},
        'United Arab Emirates': {iso2: 'AE', code: '971'},
        'United Kingdom': {iso2: 'GB', code: '44'},
        'United States': {iso2: 'US', code: '1'},
        'United States Virgin Islands': {iso2: 'VI', code: '1'},
        'Uruguay': {iso2: 'UY', code: '598'},
        'Uzbekistan': {iso2: 'UZ', code: '998'},

        'Vanuatu': {iso2: 'VU', code: '678'},
        'Vatican City': {iso2: 'VA', code: '39'},
        'Venezuela': {iso2: 'VE', code: '58'},
        'Vietnam': {iso2: 'VN', code: '84'},

        'Wallis and Futuna': {iso2: 'WF', code: '681'},
        'Western Sahara': {iso2: 'EH', code: '212'},
        'Yemen': {iso2: 'YE', code: '967'},
        'Zambia': {iso2: 'ZM', code: '260'},
        'Zimbabwe': {iso2: 'ZW', code: '263'},
    }).map(([name, {iso2, code}]) => [name, {name, iso2, code}]),
)

export const byIso2: Record<string, Country> = Object.fromEntries(Object.values(byName).map(data => [data.iso2, data]))

export const byCode: Record<string, Country[]> = Object.values(byName).reduce(
    (acc, data) => {
        ;(acc[data.code] ??= []).push(data)
        return acc
    },
    {} as Record<string, Country[]>,
)

export const overlapping = [
    {code: '1', name: 'North American Numbering Plan'},
    {code: '44', name: 'United Kingdom and Crown Dependencies'},
    {code: '39', name: 'Italy and Vatican City'},
    {code: '47', name: 'Norway and Svalbard & Jan Mayen'},
    {code: '262', name: 'Réunion and Mayotte'},
    {code: '290', name: 'Saint Helena and Tristan da Cunha'},
    {code: '590', name: 'Guadeloupe, Saint Barthélemy, and Saint Martin'},
    {code: '672', name: 'Norfolk Island and Australian Antarctic Territory'},
    {code: '212', name: 'Morocco and Western Sahara'},
]

export const longestCode = Object.keys(byCode).reduce((acc, code) => Math.max(acc, code.length), 0)
